### ISSUE TITLE
[XML validation error] encountering unrecognized namespace 'fcp', 'rism', and 'exx_nstep' in QE-7.2

### ISSUE THREAD

**Issue by yliu1240** [QEF/qeschema#39]
Hi, all!
It seems the previous XML children validation error occurs again for current QuantumEspresso-7.2 version. I'm using the previous "validation='lax'" to work around the problem in PwDocument().read() and the PwDocument().to_dict().

The following error messages from PwDocument.errors may help:
'/qes:espresso/input/control_variables', "Unexpected child with tag 'fcp' at position 18."
'/qes:espresso/input/control_variables', "Unexpected child with tag 'rism' at position 19."
'/qes:espresso/input/electron_control', "Unexpected child with tag 'exx_nstep' at position 7. Tag 'tq_smoothing' expected."

It also took me a while to figure out that to_dict() function needs a "validation" as well.

Thanks a lot and have a nice day!

Best regards,

**Comment by pietrodelugas** [comment]
Thanks!
Indeed, we need to update the default schema to the latest schema version. 
Lax is always a good option. Another way to avoid the usage of the default schema is to instantiate PwDocument directly, specifying a source file. 
`doc = PwDocument(source='mypwdata.xml') ` 
The doc object will have all data contained in the source, and you can update it with the data of any file written with a compatible schema.

**Comment by yliu1240** [comment]
> Let's keep it open until we update the default schema

OK, thank you!

Best regards,

**Comment by pietrodelugas** [comment]
the default schema is now up to date
