### ISSUE TITLE
lda_plus_u = .t. is missing from input

### ISSUE THREAD

**Issue by afonari** [QEF/qeschema#7]
Try attached xml, it is expected that lda_plus_u = .t. should be present in the .in
[FeO_LDAU_standard.txt](https://github.com/QEF/qeschema/files/6468051/FeO_LDAU_standard.txt)

**Comment by giannozz** [comment]
The presence of <dftU> implies that lda_plus_u = .t.

**Comment by afonari** [comment]
Related qexsd commit: https://github.com/QEF/qexsd/commit/a6d365433641f2b41d6155bd49b4628d3adcf51d

**Comment by pietrodelugas** [comment]
yes I forgot to add the fix here. Thanks Sasha.

**Comment by afonari** [comment]
This is a blocker to switch to qeschema (everything else seems to be working). Hopefully it is resolved soon.

**Comment by afonari** [comment]
Closed by https://github.com/QEF/qeschema/pull/12.
